package com.lacunasoftware.restpki;

import com.lacunasoftware.restpki.SubscriptionAccessModelRolesRootRolesApplicationModel;

public class ApplicationModel extends SubscriptionAccessModelRolesRootRolesApplicationModel {}